language: python
sudo: false
python:
  - 2.7
  - 3.4
  - 3.5
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true
services:
  - postgresql
  - mysql

install:
  - pip install tox-travis
before_script:
  - mysql -e 'create database test_project'
  - psql -c 'create database test_project;' -U postgres
script: tox
notifications:
  email: false
